name: report
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^1.19.1
  firebase_auth: 3.4.1
  cloud_firestore: 3.2.1
  firebase_storage: 10.3.1
  awesome_snackbar_content: ^0.0.5
  image_picker: 0.8.5+3
  geolocator: 9.0.0
  geocoding: 2.0.4
  fl_chart: 0.55.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

